export const mutationsAccount = {
  SET_TOKEN: 'SET_TOKEN',
  SET_MENUS: 'SET_MENUS',
  SET_AUTHORITIES: 'SET_AUTHORITIES',
  SET_PUBLICUSERINFO: 'SET_PUBLICUSERINFO',
  SET_MODIFY_PASSWORD_RESULT: 'SET_MODIFY_PASSWORD_RESULT'
}
