export const mutationsGlobal = {
  SET_COMPONENTS_KEEPALIVE: 'SET_COMPONENTS_KEEPALIVE',
  SET_LOADING: 'SET_LOADING',
  SET_COLLAPSE: 'SET_COLLAPSE',
  SET_PRISON: 'SET_PRISON',
  SET_NO_PAGE_PARTNERS: 'SET_NO_PAGE_PARTNERS'
}
